export const proposalSchema = {
  type: 'object', additionalProperties: false,
  required: ['title', 'summary', 'rationale', 'requires_human_review', 'confidence', 'writeback', 'evidence', 'actions'],
  properties: {
    title: { type: 'string' }, summary: { type: 'string' }, rationale: { type: 'string' }, requires_human_review: { type: 'boolean' }, confidence: { type: 'number', minimum: 0, maximum: 1 }, writeback: { type: 'string' }, evidence: { type: 'array', items: { type: 'string' }, maxItems: 12 },
    actions: { type: 'array', maxItems: 20, items: { type: 'object', additionalProperties: false, required: ['type', 'node_id', 'kind', 'label', 'description', 'owner', 'rule', 'source', 'target', 'source_handle', 'game_action', 'game_action_args', 'checkpoint_id', 'reason'], properties: {
      type: { type: 'string', enum: ['add_card', 'update_card', 'add_edge', 'remove_edge', 'game_action'] }, node_id: { type: ['string', 'null'] }, kind: { type: ['string', 'null'], enum: ['control', 'explorer', 'worker', 'query', 'server', 'agent', 'source', 'profile', 'analysis', 'impact', 'risk', 'patch', 'monitor', 'parallel', 'diagram', 'split', 'decision', 'transform', 'review', 'validation', 'output', null] }, label: { type: ['string', 'null'] }, description: { type: ['string', 'null'] }, owner: { type: ['string', 'null'] }, rule: { type: ['string', 'null'] }, source: { type: ['string', 'null'] }, target: { type: ['string', 'null'] }, source_handle: { type: ['string', 'null'], enum: ['approved', 'quarantine', 'feedback', null] }, game_action: { type: ['string', 'null'], enum: ['move_to', 'follow_route', 'interact', 'enter_vehicle', 'exit_vehicle', 'navigate_to', 'jump', 'mine_block', 'place_block', 'craft_item', 'equip_item', 'attack_entity', 'use_item', 'wait', 'stop', null] }, game_action_args: { anyOf: [{ type: 'null' }, { type: 'object', additionalProperties: false, required: ['target_x', 'target_y', 'target_z', 'entity_id', 'route_id', 'interaction', 'duration_ms', 'item_name', 'block_name', 'count', 'face', 'max_distance'], properties: { target_x: { type: ['number', 'null'] }, target_y: { type: ['number', 'null'] }, target_z: { type: ['number', 'null'] }, entity_id: { type: ['string', 'null'] }, route_id: { type: ['string', 'null'] }, interaction: { type: ['string', 'null'] }, duration_ms: { type: ['number', 'null'] }, item_name: { type: ['string', 'null'] }, block_name: { type: ['string', 'null'] }, count: { type: ['number', 'null'] }, face: { type: ['string', 'null'], enum: ['up', 'down', 'north', 'south', 'east', 'west', null] }, max_distance: { type: ['number', 'null'] } } }] }, checkpoint_id: { type: ['string', 'null'] }, reason: { type: 'string' },
    } } },
  },
} as const
